### PR TITLE
WIP: Sync TAG-review updates back into master

### PR DESCRIPTION
**Pull request by mmccool**
Ready to merge.

Make sure edits to Explainer and TAG-review message make it back to master.   Avoid clobbering the README.md.

### CODE REVIEW

**Comment by mmccool** [comment]
Note the order of the commits is messed up due to some date/time weirdness with github.   The last commit was actually me restoring the original README.md file from the master after merging in the other changes on the TAG-review branch.

**Comment by mmccool** [comment]
If we merge https://github.com/w3c/wot-architecture/pull/193 into the source of this PR before merging we can incorporate the reference fixes as well (although we should delete the reference to the TAG version of the TD spec).

**Comment by mlagally** [comment]
@mmccool Is this still WIP?

**Comment by mmccool** [comment]
No, ready to merge, if no one has any comments.  I will update the title.

**Comment by mlagally** [comment]
Rendered version: https://cdn.staticaly.com/gh/mmccool/wot-architecture/TAG-sync/index.html

**Comment by k-toumura** [comment]
To prevent cache, we can use Staticaly as Development CDN by adding `?env=dev` query string on the URL:
https://cdn.staticaly.com/gh/mmccool/wot-architecture/TAG-sync/index.html?env=dev

(see also: [cache behavior of Staticaly](https://www.staticaly.com/network#cache-behavior))

**Comment by mlagally** [comment]
Diff: https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fwot-architecture%2F&doc2=https%3A%2F%2Fcdn.staticaly.com%2Fgh%2Fmmccool%2Fwot-architecture%2Fsequences-updates%2Findex.html?env=dev

**Pull request merged**
