### PR TITLE
Clean up/expand section 9, fix ExposedThing/ConsumedThing, terminology fixes, spell check

### PR DESCRIPTION
**Pull request by mmccool**
Ready to merge. This WILL require a full review, it's (unfortunately) not just editorial...

- Figures needed "Thing Directory" changed to "Thing Directory A" (or B) to match the text.  
- All instances of ExposedThing changed to Exposed Thing and tagged (globally)
- All instances of ConsumedThing changed to Consumed Thing and tagged (globally)
- Various other bits of terminology changed, e.g. server to WoT Server where appropriate.  Note: I did sometime use "device" or "application" when I _wanted_ to be vague about whether they are clients or servers.
- Change in first paragraph focuses purpose of section on demonstrating how WoT Thing implementations are connected into various topologies.   I took out the discussion of "components" since I *think* it was a relic from when this section also discussed internal structures of implementations.   In general I thing we want to focus this section on topological and deployment issues and examples.   Content that discusses internal structure should be moved to the previous section on implementation...
- A couple of "in more complex scenarios" added.  I put these after the figures since the figures don't reflect some of the topics discussed in these paragraphs: NAT traversal with local Servient as a client opening a tunnel using a "custom" protocol; cloud applications that are servers.
- A lot more edits than I expected in all but the last section to get things aligned with the rest of the text, and in particular to not pigeonhole devices as server and cloud applications as client
- Split the last section into two sub-sections for each case.
- Spell check (global)

### CODE REVIEW

**Comment by mmccool** [comment]
PLEASE REVIEW.   Unfortunately this is not just editorial.   Not ready to merge (I need to fix some things in the figures) but the text is ready for review.

**Comment by mmccool** [comment]
Fixed ExposedThing and ConsumedThing globally, addressing https://github.com/w3c/wot-architecture/issues/171, which can be closed if this PR is merged.

**Comment by mlagally** [comment]
@mmccool Great work. 
I noticed that there are 4 respec issues in the PR, somehow the links to the following terminology entries don't work:
* WoT Client
*WoT Servient
* WoT Server

WoT Servient is called Servient in the terminology section, I suggest to rename and move.

**Comment by mmccool** [comment]
OK, let me try to fix the Respec issues.

**Comment by mlagally** [comment]
I already fixed it on my branch which I created based on yours.

**Comment by mlagally** [comment]
https://github.com/w3c/wot-architecture/pull/179

**Comment by mmccool** [comment]
Uhmm... we may have fixed the respec issues differently.   Also I found one extra untagged version of Servient that I fixed while I was at it.

**Comment by mlagally** [comment]
I suggest we keep the term WOT Servient, to be aligned with WoT Client, WoT Server.
In my PR I moved the definition of Servient to WoT servient and just made Servient a synonym for WoT Servient. Renaming it all over the text would break the flow ...

**Comment by mmccool** [comment]
How about I leave things alone for half an hour, let you patch things up, then I will check here again and if you have review comments, I can address them.   If you make PRs against my repo I can merge them though.

**Comment by mlagally** [comment]
Ok

**Comment by mmccool** [comment]
I agree with WoT Servient as opposed to just Servient, it looks odd next to WoT Server and WoT Client.   However... not the most pressing issue.  Let's just make an issue and deal with it post-TAG-submission.

**Comment by mmccool** [comment]
After merging I checked Respec and the section structure -- both look good.   However the synonym for Servient, WoT Servient, seems to be missing.   I will add it back in...

**Pull request merged**
