### PR TITLE
Restructuring (see #27)

### LINKED ISSUE #20: Git edit link pointing to wrong repo
Git edit link in SOTD section of https://w3c.github.io/wot-architecture/ seems to refer still to old repo (https://github.com/w3c/wotwg/tree/master/architecture)?

### LINKED ISSUE #21: Link other documents such as TD, Scripting, Bindings
The architecture document may be the first document people gonna read.

Hence it would be good that the Abstract/intro might describe the other documents (as suggest by @mmccool PR) and also link the other documents such as thing description, Scripting, binding...

### LINKED ISSUE #24: Connectivity Section(s)
#14 raised the issue about how to connect to a Servient running on a smartphone. This is similar to how to connect to Servient behind a firewall or NAT.

One solution is quite obvious when looking at the pattern from LWM2M: the Servient connects to the cloud with a long-lasting, bidirectional connection (e.g., CoAP-over-TLS). Yet there might be other solutions for other use cases, for instance WebRTC.

I propose to add a connectivity section or even better, add this aspect under "Deployment Scenarios" to improve the differentiation to "Mapping Variations" (which is currently more or less the figures...).

### LINKED ISSUE #27: High-level content of the document
During my current iteration, I somewhat lost my understanding of what the document currently actually offers. There is a lot of good and valid information, yet it feels a bit like a heap rather than the guidance document it should be. There is a list defining the purpose in the introduction. However, I do not see it reflected in the sections or the content:

- a guideline to the mapping between functional architecture and physical devices configuration
> This (probably) corresponds to the "Mapping Variations" section at the end
- a description of the role and functionality of each logical module
> This is the Servient architecture and somewhat building block explanation
- a reference defining what should be standardized
> Do we need this here? We already have a charter.
- a set of requirements for a WoT implementation environment.
> Not sure what this means

## My proposal

I fear that also other readers might have trouble to understand the provided information. Please tell me, if it is only me! For my personal better understanding, I would propose the following outline, which would produce a corresponding list for the purpose of the document:

### Functional Requirements
The list of requirements addressed by the WoT Architecture. Ideally, the final document does not only state the requirements, but also summarizes how they are met.

### Integration Patterns
An overview of the different integration patterns and envisioned deployments. See #9 and our architecture [overview figure](http://w3c.github.io/wot/charters/wot-wg-2016-figure.png)

### WoT Building Blocks and Servient Architecture
An introduction to the WoT building blocks. The result of combing these is either a Thing (only TD) or a WoT Servient (also Protocol Bindings and optionally the Scripting API). I guess this should be understood before looking at the deployment scenarios.
### Deployment Scenarios
Implementation guidelines for the different deployment scenarios. The current Section 5 answers what kind of discovery is required and what interactions are possible (my interpretation of the "API" lists). Issue #24 proposes to add guidance on how to enable connectivity in each scenario.

### Functional Roles of Servients*

*Let's think about better titles.

I find "Mapping Variations" quite misleading and the focus on specific devices in the sub-section titles is confusing, too. I think the purpose of the current Section 6 is to show which functional roles a Servient could serve (e.g., simply as state-of-the-art implementation of a Thing, or as gateway, or as cloud proxy, etc.). . Please confirm my assumption about this purpose.

### Security Considerations
Space to note everything that has to be considered for a secure WoT deployment...

---

Please let me know if you agree with this, as I want to avoid rewriting to much without consensus.

### PR DESCRIPTION
**Pull request by mkovatsc**
This pull request implements the changes proposed in #27 and fixes other issues:
fixes #27
fixes #24 
fixes #21
fixes #20

There are small additions to the proposed outline that became apparent when working on the document.

[HTML diff](https://services.w3.org/htmldiff?doc1=https%3A%2F%2Fw3c.github.io%2Fwot-architecture%2F&doc2=https%3A%2F%2Fraw.githubusercontent.com%2Fmkovatsc%2Fwot-architecture%2Frestructuring%2Findex.html) (if of any use with these massive changes...)

Furthermore, based on the amount of work put into the restructuring and terminology definitions, I added myself to the list of editors.
@mmccool and @Kazuo-Kajimoto, do you agree with this?

Can be merged when both other co-chairs +1.

### CODE REVIEW

**Comment by Kazuo-Kajimoto** [comment]
Thank you Mathias, I agree.

**Comment by mkovatsc** [comment]
@mmccool bump

**Comment by Kazuo-Kajimoto** [comment]
May I merge right now ?

**Comment by mmccool** [comment]
Matthias,
Yes, I agree with adding you as an Editor and also with the merge.  As we won't be adding a security considerations section until after the FPWD, it would be however useful to add an Editor's note to that effect.   Go ahead and do the merge after that, please.

**Pull request merged**
