### PR TITLE
Update Figures 27 and 28 (Servient implementation) and also 25

### PR DESCRIPTION
**Pull request by mmccool**
Resolves Issue https://github.com/w3c/wot-architecture/issues/232.   Note the figure numbering has changed though and I also made edits to a related figure (the building blocks figure) for consistency.

### CODE REVIEW

**Comment by mlagally** [comment]
Call on 25.4.:
Consider removing the "Thing" boxes below the protocol binding.
Consider removing the protocol boxes within the protocol binding block.

**Comment by mlagally** [comment]
@mkovatsc can you please comment?

**Comment by mmccool** [comment]
I need to do some updates to get a single PPT master after merging Matthias' new version.

**Comment by mmccool** [comment]
Ready to merge.

**Comment by mkovatsc** [comment]
I now implemented my change proposal in #251.

Tried to simplify without losing details and aligned the colors. A major change is maybe that I list the data schema explicitly. It is part of the Interaction Affordances, but we also list Security and Bindings explicitly. Our alignment with JSON Schema is quite a feature and having data schema support is quite essential considering "the competition" at One Data Model.

**Comment by mkovatsc** [comment]
If you agree, please close this PR and merge #251 instead.

**Comment by mlagally** [comment]
@mmccool Plese confirm if we can close this PR without merging

**Pull request closed without merging**
