### PR TITLE
Cr candidate 3

### PR DESCRIPTION
**Pull request by mlagally**

### CODE REVIEW

**Comment by mkovatsc** [comment]
Does this include the other open PRs?
Are the other PRs planned to be merged?
When?

I unfortunately cannot see what the actual status is, given there are unclear PRs pending that might be merged or not...

**Comment by mlagally** [comment]
@mkovatsc 

This is the CR-Candidate-3 - it includes all PRs that were available 
this morning at at 7:54 am CEST - see my corresponding mail to the WOG-WG/IG reflector. 

Issue 329 contributors  - #330 opened 14 hours ago by mlagally 
Editorial Chapter 9 - #321 opened a day ago by mlagally 
Issue 134 device registers itself pattern - #319 opened a day ago by mlagally 
Issue 311 capitalisation of headings - #318 opened a day ago by mlagally 
Improve Data Schema illustration - #317 opened a day ago by k-toumura 
Editorial chapter 8 - #302 opened 2 days ago by mlagally

**Comment by mkovatsc** [comment]
So open pull requests are already half merged?

How should I include fixes now? Post them as text in the issues such as #333 ?

**Comment by mlagally** [comment]
You can create a local branch of the CR-candidate-3 in your fork and create new branches / PRs against the master. Please don't update any of the old PRs.

**Pull request merged**
