### PR TITLE
Fix Web Thing text and figure and fix #230 (overview figure)

### LINKED ISSUE #230: Align Figure 15 with new terminology
Changes include:
- removing thing from Web browser
- Adding intermediary to gateway
- Moving TD to "existing device"
- align arrows
- indicate "Consumer" in combined thing

### PR DESCRIPTION
**Pull request by mkovatsc**
See #230 

As the overview reuses the Thing illustration from Section 6.3, I also fixed that section and figure.

### CODE REVIEW

**Comment by mlagally** [comment]
This looks very good.

A few comments:

1. Multiple TDs
I understand that you want to indicate that there may be more than one TD for things at the edge or in the cloud., however IMO in this overview picture it might be one level of detail too deep. 

2. Color semantics
Until now we used green icons for TDs, now they are orange. I'm not sure that we use these colors consistently all over the spec - please double-check

**Comment by k-toumura** [comment]
> 2. Color semantics
>    Until now we used green icons for TDs, now they are orange. I'm not sure that we use these colors consistently all over the spec - please double-check.

I think this is @mkovatsc 's proposal of new color semantics (see [comment](https://github.com/w3c/wot-architecture/pull/238#issuecomment-485873974) in PR #238).

@mkovatsc , is it right?

**Comment by k-toumura** [comment]
https://cdn.staticaly.com/gh/w3c/wot-architecture/aa5ac0a/index.html#architecture-abstract

**Comment by mlagally** [comment]
Call on 25.4.:

Please remove additional TDs - Color consistency should be addressed on the document as a whole.
See issue: https://github.com/w3c/wot-architecture/issues/228

**Pull request merged**
