### PR TITLE
Updates to Security and Privacy Questionnaire

### PR DESCRIPTION
**Pull request by mmccool**
At our Security TF call on Monday, March 25 we made some edits to our responses to the Security and Privacy Questionnaire, but did not update the version submitted for TAG review. I've created this PR to review the changes.

This replaces https://github.com/w3c/wot-architecture/pull/184 (basically, I branched master into TAG-review-updates so that other unrelated updates to the master would not affect this update).   **I will delete this branch once this PR is merged; the purpose of the TAG-review-updates branch is just to stage updates like this, not to serve as another review target.**

### CODE REVIEW

**Comment by mmccool** [comment]
Note: in the diffs some updates to the TAG review request are shown.  These are not real; both the master and the TAG-review branch, AND the TAG-review-updates branch have been updated to the version actually submitted.  I'm not sure why the diff is showing this as a change, but at any rate, the result of the PR will be the correct version.

**Comment by mmccool** [comment]
OK, I have finished reviewing the updates and am personally happy with them now.   For each question I also added explicitly highlighted short answers (Yes, No, N/A, etc) and made sure the introduction and each response was applicable to both the WoT Architecture and WoT Thing Description document (since we are using it for both).  I also added some hyperlinks back to the questionnaire and numbered the questions to make them easier to cross-reference.

Please comment, I'd like to wrap this up and update the TAG review branch as soon as possible.

**Comment by mmccool** [comment]
I'm going to have to merge this soon because the updates make it clear this also applies to the TD spec, the TD spec TAG submission refers to this, and I expect the W3C Security group to start reading it soon.   I will merge it after an hour if I don't see any comments or reviews.

**Comment by takuki** [comment]
The first link to TD is pointing to Architecture document. 

> [WoT

 Thing Description](https://github.com/w3c/wot-architecture) document.

**Comment by takuki** [comment]
Also, when I access [security_and_privacy.md ](https://github.com/w3c/wot-architecture/blob/TAG-review/proposals/security_and_privacy.md) on TAG-review branch, it says it was updated 23 hours ago. Not sure if I am looking at the latest one.

**Comment by takuki** [comment]
The [TAG review request](https://github.com/w3ctag/design-reviews/issues/357) points to the version on master branch. Should not we point to the one on TAG-review branch?

**Comment by mmccool** [comment]
Taki,
The link points to the wot-architecture repo because there is only one document used by both the TD and Arch TAG submissions.   The link is correct in the actual TAG issues (pointing to wot-architecture/TAG-review) but I have not copied the contents of the TAG issues back to these repos yet.   I will sync things up shortly.

The "updated 23 hours" ago thing was due to the clock on my VirtualBox Linux system losing time every time I "paused" it.   I fixed that today (finally).   There is some other bug I haven't figured out that sometimes shows commits occuring in the future, but I think that is on github's side.  Bottom line: don't trust the sequence of events or dates...

Anyway, it is merged now, and I checked the links in the actual submitted TAG issues both point to the right place.

**Comment by mmccool** [comment]
PS the version of the doc on the master branch is indeed out of date.   I have a PR ready to go to sync things up again, but I first want to fix the TAG submission to match what is in the issue tracker.

**Comment by takuki** [comment]
Hi @mmccool , I just made a PR #190 to fix a link in the security_and_privacy.md document.

**Pull request merged**
