### PR TITLE
Harmonized figure style

### PR DESCRIPTION
**Pull request by mkovatsc**
This pull requests replaces the figures (except Section 5) and adds the figure sources.

(Bumped after linking GitHub account with W3C profile)

### CODE REVIEW

**Comment by mkovatsc** [comment]
Figures have been merged manually, closing.

**Comment by mkovatsc** [comment]
Actually outdated figures were merged.

**Comment by mkovatsc** [comment]
I kept the textual changes to a minimum (only to align with the figures).
Thus, this needs merging soon to fix further issues in the text.

**Comment by Kazuo-Kajimoto** [comment]
Merged #23 issue contributed by Mathias

**Pull request merged**
