### PR TITLE
Add and update figures in section 6. WoT Architecture

### PR DESCRIPTION
**Pull request by k-toumura**
(for issues #228, etc.)
In this PR, I will update and add figures in section 6. WoT Architecture.
To discuss and feedback quickly, I made a [draft PR](https://github.blog/2019-02-14-introducing-draft-pull-requests/) for this.

Firstly, I added the figures in 6.1 Overview (see issue #229).
[Here is a link](https://cdn.staticaly.com/gh/k-toumura/wot-architecture/sec-arch-figures/index.html?env=dev#sec-architecture-overview) to the browsable HTML of the index.html.

@mkovatsc I'd appreciate it if you could give me your opinion on these figures.

### CODE REVIEW

**Comment by mkovatsc** [comment]
Looks very good! Once we have the content right of all figures, we should probably do another pass to align colors -- and also reduce the "eye cancer" from disharmonic color schemes :)

**Comment by mlagally** [comment]
This looks good!

On the "intermediary" figure the dotted green line should also have a label as in the previous one.

On the "linked" figure, I'm not clear about the purpose of the blue arrows.

**Comment by k-toumura** [comment]
> Once we have the content right of all figures, we should probably do another pass to align colors -- and also reduce the "eye cancer" from disharmonic color schemes (later complex figures) :)

I see.  If you have some preference on colors (TD for green etc.), please let me know.

> On the "intermediary" figure the dotted green line should also have a label as in the previous one.

I added a label on recent commit https://github.com/w3c/wot-architecture/pull/238/commits/6aa4328aa461bfd78e2a515b415e610012e44214 . 

> On the "linked" figure, I'm not clear about the purpose of the blue arrows.

This depicts a relations between Things (eg. a switch Thing controlling a light Thing, etc.).
In use case figures, blue arrows depicts interaction, so I changed color of the arrows to gray.

**Comment by k-toumura** [comment]
I changed a state of this PR from draft to 'Ready to review'.   Remaining figures will update on following PRs:
- PR #242 will fix Overview figure and  Web Thing figure.
- PR #227 will fix figures in System Configuration.

I'll adjust these figure to make consistent with other figures, on another PR.

**Pull request merged**
