### PR TITLE
Generate static HTML file for WD publication (for CR candidate)

### PR DESCRIPTION
**Pull request by k-toumura**
~~https://cdn.statically.io/gh/w3c/wot-architecture/c51c97e8b60c4ccebbd394ccae5b6a5edf1165e4/publication/ver11/2-cr/Overview.html~~

Updated(7/1): https://cdn.statically.io/gh/w3c/wot-architecture/8e579dccc052bbee7e302eb4455fcb533063d077/publication/ver11/2-wd/Overview.html

### CODE REVIEW

**Comment by k-toumura** [comment]
- incorporate recent change (as of 2022-07-01 01:18UTC)
- move directory from `2-cr/` to `2-wd/`
- change `specStatus` from `ED` to `WD`
- copy `/testing/atrisk.css` to `./testing/atrisk.css`
- update an URI of implementation report from `...report.html` to `...report11.html`

@mmccool @mlagally  If there is no problem, I'll change status of PR to 'Ready for review'

**Comment by k-toumura** [comment]
rendered version: https://cdn.statically.io/gh/w3c/wot-architecture/8e579dccc052bbee7e302eb4455fcb533063d077/publication/ver11/2-wd/Overview.html

**Comment by k-toumura** [comment]
[Result](https://www.w3.org/pubrules/?url=https%3A%2F%2Fcdn.statically.io%2Fgh%2Fw3c%2Fwot-architecture%2F8e579dccc052bbee7e302eb4455fcb533063d077%2Fpublication%2Fver11%2F2-wd%2FOverview.html&profile=WD&validation=simple-validation&informativeOnly=false&echidnaReady=false&patentPolicy=pp2004) of Pubrules 6.1.9: 
- All tests passed
- 4 warnings
- 10 advices

**Comment by mlagally** [comment]
@k-toumura 
The version at staticaly, still is an "Editor's draft". Can you please check?

**Comment by k-toumura** [comment]
> @k-toumura The version at staticaly, still is an "Editor's draft". Can you please check?
The link in third comment is recent version, and it is already reflects the changes in second comment.
To avoid confusion, I also updated a link in first comment.

**Pull request merged**
