### PR TITLE
Diagram rearrange

### PR DESCRIPTION
**Pull request by k-toumura**
For #228:
- Consistent color semantics
- Add 'Data Schema' in figure of Section 8
- Higher contrast between text and background for accessibility
- Use separate directory/source PPTX for each section

### CODE REVIEW

**Comment by mkovatsc** [comment]
Unfortunately, @mlagally voided major updates of Figures wot-thing-scripting and wot-thing-native while merging (see #294).

Thus, your figure updates are based on an invalid status including the power point sources...

**Comment by k-toumura** [comment]
> Unfortunately, @mlagally voided major updates of Figures wot-thing-scripting and wot-thing-native while merging (see #294).
> 
> Thus, your figure updates are based on an invalid status including the power point sources...

Sure...,  I'll update the PR using following PPTX(pp. 9-10):
https://github.com/w3c/wot-architecture/blob/8a41d9580a88cf48177f4ae6ef61d4f459092843/images/wot-architecture-figures-new4.pptx

**Comment by k-toumura** [comment]
Salvaged and fixed figures wot-thing-scripting and wot-thing-native.

**Comment by mlagally** [comment]
@k-toumura Please take a look at the figures in PR: https://github.com/w3c/wot-architecture/pull/297
I restored them, since they were overwritten by some other merge.

**Comment by k-toumura** [comment]
> @k-toumura Please take a look at the figures in PR: #297
> I restored them, since they were overwritten by some other merge.

I updated figures based on PR #297.   Please check following figures.
- [update of images/wot-building-blocks-abstract.png](https://github.com/w3c/wot-architecture/blob/deb64890fcea6a05268f22eb04c9b439da3356b7/images/bblocks/abstract.png)
- [update of images/wot-thing-scripting.png](https://github.com/w3c/wot-architecture/blob/deb64890fcea6a05268f22eb04c9b439da3356b7/images/servient/wot-thing-scripting.png)
- [update of images/wot-thing-native.png](https://github.com/w3c/wot-architecture/blob/deb64890fcea6a05268f22eb04c9b439da3356b7/images/servient/wot-thing-native.png)

**Comment by mkovatsc** [comment]
Somehow the PNG export is distorted (spaces between public sec. text and box margin, lower right corner of TD). What program and version are you using to create the PNGs?

**Comment by mkovatsc** [comment]
The figures currently in the master
* https://w3c.github.io/wot-architecture/images/wot-building-blocks-abstract.png
* https://w3c.github.io/wot-architecture/images/wot-thing-scripting.png
* https://w3c.github.io/wot-architecture/images/wot-thing-native.png
* https://w3c.github.io/wot-architecture/images/wot-thing-existing.png
look good.

The only missing improvement is coloring the Exposed/Consumed Things also in blue and only indicate the TD through the border -- which is a good change!

Maybe we can have the API boxes and and Exposed/Consumed Thing boxes in the same shade of blue to further reduce the color noise?

**Comment by k-toumura** [comment]
> Somehow the PNG export is distorted (spaces between public sec. text and box margin, lower right corner of TD). What program and version are you using to create the PNGs?

I'm using PowerPoint (office365) on Windows 10, and generate PNG by 'save as picture' in contextual menu.
I also changed font from Calibli to Noto Sans for portability.   This is a cause of some distortion in margins...

**Comment by mkovatsc** [comment]
> I'm using PowerPoint (office365) on Windows 10, and generate PNG by 'save as picture' in contextual menu.
I also changed font from Calibli to Noto Sans for portability. This is a cause of some distortion in margins...

I see. I have the same workflow, so it might be just the font. The corner rendering is still weird

Interestingly, western Windows distributions do not have Noto Sans. I assumed Microsoft's Calibri would be part of every distribution, and hence better for portability.

**Comment by k-toumura** [comment]
Fixed following problems:
- have the API boxes and and Exposed/Consumed Thing boxes in the same shade of blue 
- TD corner rendering
  - [example](https://github.com/w3c/wot-architecture/blob/074f15bc9ab65bd9351b0936f8302131d15d7068/images/servient/wot-thing-scripting.png)

I'm also preparing SVG version of these diagrams.  This is one of the reason I use a Noto Sans web font.  
But it need some complicated workflow (export as .emf, import to Inkscape, export as SVG, some minor tweak by hand), so currently I focus to my attention to make PNGs consistently.

**Comment by mlagally** [comment]
@k-toumura We can replace the PNG versions of the diagrams with SVG even after CR transition,
since the content does not change.

**Comment by mlagally** [comment]
approved to merge in call on 7.5.

**Pull request closed without merging**
