### PR TITLE
Improve Data Schema illustration

### PR DESCRIPTION
**Pull request by k-toumura**
For issue #312.

### CODE REVIEW

**Comment by mkovatsc** [comment]
Looks good!

While you are at it, could you widen the Thing boxes in [overview](https://raw.githubusercontent.com/w3c/wot-architecture/4cf5efe6f26a9ef430a22eca203092862145a982/images/architecture/overview.png), so that "Interaction Affordances" as some margin to the edge of its box?

**Comment by k-toumura** [comment]
> While you are at it, could you widen the Thing boxes in [overview](https://raw.githubusercontent.com/w3c/wot-architecture/4cf5efe6f26a9ef430a22eca203092862145a982/images/architecture/overview.png), so that "Interaction Affordances" as some margin to the edge of its box?

Updated in commit https://github.com/w3c/wot-architecture/pull/317/commits/a6ad4a60fe722b7516acc223b2a988276d5be1b5.

**Comment by mkovatsc** [comment]
Thanks!

Ready to merge.

**Comment by mlagally** [comment]
@k-toumura Can you please take another look at figure 27.
(images/servient/wot-thing-scripting.png)
The text talks about the WoT runtime, however the corresponding block in the image still is labelled "Scripting WoT Runtime" 
Can you please rename to "WoT Runtime"?

**Comment by mkovatsc** [comment]
We had text that explains the label "Scripting WoT Runtime", a WoT Runtime that is also a scripting runtime system. The figure says "Scripting WoT Runtime" to reflect this combination for the WoT Scripting API.

**Comment by mlagally** [comment]
agreed in Arch call on 9.5.: closing without merging to master, since it is included in CR-candidate-3

**Pull request closed without merging**
